### ISSUE TITLE
Update Teleport Section in README

### ISSUE THREAD

**Issue by HCastano** [paritytech/canvas#114]
The Polkadot JS UI [recently added functionality](https://github.com/polkadot-js/apps/pull/6681) for a standalone "teleport" tab for the Rococo network (this already existed in Westend for example). We should update the README to use that instead of showing the manually crafted XCM extrinsic.

**Comment by Geff22** [comment]
> Пользовательский интерфейс Polkadot JS [недавно добавил функциональность](https://github.com/polkadot-js/apps/pull/6681) для отдельной вкладки "телепорт" для сети Rococo (например, это уже существовало в Westend). Мы должны обновить файл README, чтобы использовать его вместо отображения внешнего XCM, созданного вручную.

**Comment by HCastano** [comment]
Closed by #120.
