### ISSUE TITLE
Parachain

### ISSUE THREAD

**Issue by ascjones** [paritytech/canvas#30]
Currently `canvas` runs as a solo chain, but ultimately it should be a parachain. This will involve migrating to use `cumulus`, and if possible still allow it to run as a solochain for the testnet,  [Moonbeam](https://github.com/PureStake/moonbeam) appear to have achieved something along those lines.

According to @athei, there are still some outstanding issues which need to be resolved before the `contracts` pallet will work on a parachain:

- [ ] Storage transactions
- [ ] Child tries

**Comment by ascjones** [comment]
>     * [ ]  Storage transactions
>     * [ ]  Child tries

According to @bkchr these are both already supported

**Comment by athei** [comment]
Then `pallet_contracts` should be able to run as a parachain as-is. I would recommend testing as standalone first, though. Testing two new technologies at the same time makes debugging harder.

Contracts are not new but there are a lot of changes since the last release.

**Comment by zqhxuyuan** [comment]
any update on parachain compatiblity? as the latest cumulus comes to 0.9.x series

**Comment by ascjones** [comment]
I haven't done anything on it recently, been busy with substrate metadata work. 

As soon as I am done with the metadata work I will resume on this.

**Comment by HCastano** [comment]
Closed by https://github.com/paritytech/canvas/pull/73.
