### ISSUE TITLE
[QUESTION] How to increase block gas limit

### ISSUE THREAD

**Issue by bakasura980** [paritytech/canvas#61]
Need some help to understand what needs to be changed to increase the block gas limit

**Comment by HCastano** [comment]
@bakasura980 As far as I know, the gas limit is tied to the maximum _weight_ (unit of compute) allowed by the runtime. This can in turn be tweaked with the [`MAXIMUM_BLOCK_WEIGHT`](https://github.com/paritytech/canvas/blob/39ab413e2dc37905affccf2686c4cf97d5bb68bf/runtime/src/lib.rs#L254) constant. I believe `weight` and `gas` are 1:1 equivalent at the moment, but maybe @athei can confirm.

**Comment by athei** [comment]
This is correct. There is no separate block gas limit.
